name: audit-and-lint
on: [push]
jobs:
  install-audit-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Cache NPM dependencies
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Package auditory
        run: yarn audit

      - name: Lint the source
        run: yarn lint
